### ISSUE TITLE
Clockwise & counterclockwise switched around

### ISSUE THREAD

**Issue by expandingv0id** [robol/wacom-manager#1]
Hey, works fine, just clockwise and counterclockwise are switched for me. 180 degrees is fine.
Also any chance you could add support for button binding?
Wacom CTH-490
![image](https://user-images.githubusercontent.com/69422080/90955051-67647000-e47a-11ea-94b2-53f535d0dc63.png)

**Comment by robol** [comment]
The code handling the rotation just calls ```xsetwacom```, passing the relevant options: ```cw``` for clockwise, and ```ccw``` for counter-clockwise. Does calling ```xsetwacom``` directly works for you, or is that one also swapped? In the latter case, I suspect that the problem is in the driver. I had a quick look at the code and it looks correct, as far as I can tell.

**Comment by expandingv0id** [comment]
Yes you were correct. The problem is in xsetwacom. Maybe it's not detecting my tablet model corretly. Also I had to set the rotation for my stylus which I'm not sure is correct either
![image](https://user-images.githubusercontent.com/69422080/91084524-6b47ec00-e64c-11ea-9bc3-9c320c23bf2b.png)
